name: Build and Upload Drawables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config FA token
        run: |
          npm config set @fortawesome:registry https://npm.fontawesome.com/
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FA_PACKAGE_MANAGER_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm install
      
      - name: Log folder
        run: mkdir -p tmp

      - name: Build
        run: npm run build

      - name: Clean
        run: npm run clean

      - name: Check for changes, commits and push
        id: check_changes
        run: |
            if git diff --quiet; then
              echo "No changes in the repository. Skipping commit and push."
              echo "changes=false" >> $GITHUB_ENV
            else
              echo "Changes detected in the repository."
              echo "changes=true" >> $GITHUB_ENV
              git config user.name "GitHub Action"
              git config user.email "action@github.com"
              git add chrome
              git add clean.log
              git add build.log
              git commit -m "Drawables update - ${{ github.run_id }}"
              git push origin ${{ github.ref }}
            fi